version: '3.8'

services:
  nextjs:
    build: .
    container_name: next-app
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=${NEXT_PUBLIC_ENV}
      - API_BASE_URL=${NEXT_PUBLIC_API_URL}
    command: npm run dev
